Update r.yml

diff --git a/.github/workflows/r.yml b/.github/workflows/r.yml
--- a/.github/workflows/r.yml
+++ b/.github/workflows/r.yml
@@ -1,40 +1,74 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-#
-# See https://github.com/r-lib/actions/tree/master/examples#readme for
-# additional example workflows available for the R community.
-
-name: R
+name: ETL workflow
 
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-permissions:
-  contents: read
+    branches: [ main ]
+  schedule:
+    - cron: '0 */24 * * *' # Runs every 24 hours
 
 jobs:
   build:
-    runs-on: macos-latest
-    strategy:
-      matrix:
-        r-version: ['3.6.3', '4.1.1']
-
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up R ${{ matrix.r-version }}
-        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
+      - name: Checkout code
+        uses: actions/checkout@v2
+        
+      - name: Setup R environment
+        uses: r-lib/actions/setup-r@v2
         with:
-          r-version: ${{ matrix.r-version }}
-      - name: Install dependencies
+          r-version: '4.2.0'
+          
+      - name: Cache R packages
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.R_LIBS_USER }}
+          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
+          restore-keys: |
+            ${{ runner.os }}-r-
+          
+      - name: Create figures directory
+        run: mkdir -p figures
+          
+      - name: Install packages
+        if: steps.cache.outputs.cache-hit != 'true'
         run: |
-          install.packages(c("remotes", "rcmdcheck"))
-          remotes::install_deps(dependencies = TRUE)
-        shell: Rscript {0}
-      - name: Check
-        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
-        shell: Rscript {0}
+          Rscript -e 'install.packages(c("ggplot2", "dplyr", "readr", "RSQLite", "DBI"))'
+          
+      - name: Execute R script
+        run: |
+          Rscript R_codes/Workflow.R
+          
+      - name: Execute Data Analysis
+        run: |
+          Rscript R_codes/Query_workflow.R
+      - name: Add database changes and commit
+        run: |
+          git config --global user.email "hanth.ibc55@gmail.com"
+          git config --global user.name "hanth13"
+          git add ecommerce.db
+          git add --all figures/
+          git commit -m "Update database" || echo "No changes to commit"
+          # Check if error logs exist
+          if [ -d "Error logs" ] && [ "$(ls -A Error\ logs)" ]; then
+            echo "Error logs exist"
+            # Create error logs folder
+            mkdir -p "Error logs"
+            # Write error_log.txt
+            echo "Errors:" > "Error logs/error_log.txt"
+            # Append each error to the error_log.txt file
+            for error in Error\ logs/*; do
+              cat "$error" >> "Error logs/error_log.txt"
+              echo "" >> "Error logs/error_log.txt"  # Add a newline after each error
+            done
+            # Commit error logs
+            git add "Error logs/error_log.txt"
+            git commit -m "Add error log" || echo "No error log changes to commit"
+          else
+            echo "No error logs found"
+          fi
+      
+      - name: Push changes
+        uses: ad-m/github-push-action@v0.6.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: main
